### ISSUE TITLE
i don't understand 

### ISSUE THREAD

**Issue by lillshyguy** [Dylancyclone/VMF2OBJ#26]
Python: Traceback (most recent call last):
  File "C:\Users\freeb\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\__init__.py", line 748, in execute
    importer.load(self.filepath, context, self.map_data_path)
  File "C:\Users\freeb\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\import_vmf.py", line 140, in load
    vmf = vmfpy.VMF(open(file_path, encoding="utf-8"), self._vmf_fs)
  File "C:\Users\freeb\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 721, in __init__
    self.editorversion: Optional[int] = self._parse_int_str("editorversion", versioninfo)
  File "C:\Users\freeb\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 77, in _parse_int_str
    value = self._parse_str(name, vdict)
  File "C:\Users\freeb\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_import_vmf\deps\vmfpy\__init__.py", line 66, in _parse_str
    raise VMFParseException(f"{full_name} doesn't exist", self._context)
vmfpy.VMFParseException: VMF parsing failed:  editorversion doesn't exist

location: <unknown location>:-1

**Comment by Dylancyclone** [comment]
Hi, I think you've got the wrong repository. Your error describes `io_import_vmf`, which I believe is from this repo: https://github.com/lasa01/io_import_vmf
